
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS `COMPLETION`;
CREATE TABLE `COMPLETION` (
  `ID_COMPLETION` int(11) NOT NULL,
  `ID_TASK` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `SUBMITTED_BY` int(11) NOT NULL,
  `APPROVED_BY` int(11) DEFAULT NULL,
  `POINTS` int(11) NOT NULL,
  `COMPLETED_AT` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

DROP TABLE IF EXISTS `HOUSEHOLD`;
CREATE TABLE `HOUSEHOLD` (
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `HOUSEHOLD_NAME` varchar(255) NOT NULL,
  `INVITE_LINK` varchar(1000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `HOUSEHOLD_MEMBER`;
CREATE TABLE `HOUSEHOLD_MEMBER` (
  `ID_USER` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `ROLE` enum('admin','member') NOT NULL DEFAULT 'member'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


-- Trigger: Create points record when a user joins a household
DROP TRIGGER IF EXISTS `tr_create_points_on_household_join`;
DELIMITER $$
CREATE TRIGGER `tr_create_points_on_household_join` AFTER INSERT ON `HOUSEHOLD_MEMBER` FOR EACH ROW BEGIN
  INSERT INTO `POINTS` (`ID_USER`, `ID_HOUSEHOLD`, `TOTAL_POINTS`)
  VALUES (NEW.`ID_USER`, NEW.`ID_HOUSEHOLD`, 0)
  ON DUPLICATE KEY UPDATE `TOTAL_POINTS` = `TOTAL_POINTS`;
END
$$
DELIMITER ;


-- Trigger: Notify user when their task is approved (COMPLETION insert)
DROP TRIGGER IF EXISTS `tr_notify_task_approved`;
DELIMITER $$
CREATE TRIGGER `tr_notify_task_approved` AFTER INSERT ON `COMPLETION` FOR EACH ROW
BEGIN
  INSERT INTO `NOTIFICATION` (
    `ID_USER`,
    `NOTIFICATION_TITLE`,
    `NOTIFICATION_MESSAGE`,
    `IS_READ`,
    `NOTIFICATION_CREATED`,
    `NOTIFICATION_TYPE`,
    `REFERENCE_ID`
  ) VALUES (
    NEW.`SUBMITTED_BY`,
    'Task Approved',
    CONCAT('Your task (ID: ', NEW.`ID_TASK`, ') has been approved.'),
    0,
    NOW(),
    'completion',
    NEW.`ID_COMPLETION`
  );
END$$
DELIMITER ;

DROP TABLE IF EXISTS `INVITATION`;
CREATE TABLE `INVITATION` (
  `ID_INVITATION` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `INVITED_EMAIL` varchar(300) NOT NULL,
  `INVITED_BY` int(11) NOT NULL,
  `STATUS` varchar(20) DEFAULT 'pending'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `NOTIFICATION`;
CREATE TABLE `NOTIFICATION` (
  `ID_NOTIFICATION` int(11) NOT NULL,
  `ID_USER` int(11) NOT NULL,
  `NOTIFICATION_TITLE` varchar(255) DEFAULT NULL,
  `NOTIFICATION_MESSAGE` varchar(1000) DEFAULT NULL,
  `IS_READ` tinyint(1) DEFAULT 0,
  `NOTIFICATION_CREATED` datetime DEFAULT current_timestamp(),
  `NOTIFICATION_TYPE` varchar(30) NOT NULL,
  `REFERENCE_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `POINTS`;
CREATE TABLE `POINTS` (
  `ID_USER` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `TOTAL_POINTS` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `PROGRESS`;
CREATE TABLE `PROGRESS` (
  `ID_PROGRESS` int(11) NOT NULL,
  `ID_TASK` int(11) NOT NULL,
  `ID_USER` int(11) NOT NULL,
  `JOINED_AT` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `REWARDS_CATALOGUE`;
CREATE TABLE `REWARDS_CATALOGUE` (
  `ID_REWARD` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `ID_USER` int(11) DEFAULT NULL,
  `ID_COMPLETION` int(11) DEFAULT NULL,
  `REWARD_NAME` varchar(255) NOT NULL,
  `REWARD_DESCRIPTION` text DEFAULT NULL,
  `POINTS_TO_DISCOUNT` int(11) NOT NULL,
  `IS_ACTIVE` tinyint(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `TASK`;
CREATE TABLE `TASK` (
  `ID_TASK` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `ID_USER` int(11) DEFAULT NULL,
  `TASK_NAME` varchar(255) NOT NULL,
  `TASK_DESCRIPTION` text DEFAULT NULL,
  `TASK_POINT` int(11) NOT NULL,
  `IMAGE_BEFORE` varchar(1000) DEFAULT NULL,
  `IMAGE_AFTER` varchar(1000) DEFAULT NULL,
  `TASK_CREATED` datetime DEFAULT current_timestamp(),
  `TASK_STATUS` varchar(100) NOT NULL,
  `AI_VALIDATION` tinyint(1) NULL DEFAULT 0


-- Trigger: Notify creator when a task with AI_VALIDATION=1 changes to 'pending'
DROP TRIGGER IF EXISTS `tr_notify_ai_pending_task`;
DELIMITER $$
CREATE TRIGGER `tr_notify_ai_pending_task` AFTER UPDATE ON `TASK` FOR EACH ROW
BEGIN
  IF NEW.`TASK_STATUS` = 'pending' AND NEW.`AI_VALIDATION` = 0 AND OLD.`TASK_STATUS` <> 'pending' THEN
    INSERT INTO `NOTIFICATION` (
      `ID_USER`,
      `NOTIFICATION_TITLE`,
      `NOTIFICATION_MESSAGE`,
      `IS_READ`,
      `NOTIFICATION_CREATED`,
      `NOTIFICATION_TYPE`,
      `REFERENCE_ID`
    ) VALUES (
      NEW.`ID_USER`,
      'Task Pending Approval',
      CONCAT('Your task "', NEW.`TASK_NAME`, '" is pending AI approval.'),
      0,
      NOW(),
      'ai_validation',
      NEW.`ID_TASK`
    );
  END IF;
END$$
DELIMITER ;
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID_USER` int(11) NOT NULL,
  `USER_NAME` varchar(255) NOT NULL,
  `USER_EMAIL` varchar(255) NOT NULL,
  `USER_PASSWORD` varchar(255) NOT NULL,
  `AVATAR` longblob DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


ALTER TABLE `COMPLETION`
  ADD PRIMARY KEY (`ID_COMPLETION`),
  ADD KEY `ID_TASK` (`ID_TASK`),
  ADD KEY `SUBMITTED_BY` (`SUBMITTED_BY`);

ALTER TABLE `HOUSEHOLD`
  ADD PRIMARY KEY (`ID_HOUSEHOLD`);

ALTER TABLE `HOUSEHOLD_MEMBER`
  ADD PRIMARY KEY (`ID_USER`,`ID_HOUSEHOLD`),
  ADD KEY `ID_HOUSEHOLD` (`ID_HOUSEHOLD`);

ALTER TABLE `INVITATION`
  ADD PRIMARY KEY (`ID_INVITATION`),
  ADD KEY `ID_HOUSEHOLD` (`ID_HOUSEHOLD`),
  ADD KEY `INVITED_BY` (`INVITED_BY`);

ALTER TABLE `NOTIFICATION`
  ADD PRIMARY KEY (`ID_NOTIFICATION`),
  ADD KEY `ID_USER` (`ID_USER`),
  ADD KEY `REFERENCE_ID` (`REFERENCE_ID`);

ALTER TABLE `POINTS`
  ADD PRIMARY KEY (`ID_USER`,`ID_HOUSEHOLD`),
  ADD KEY `ID_HOUSEHOLD` (`ID_HOUSEHOLD`);

ALTER TABLE `PROGRESS`
  ADD PRIMARY KEY (`ID_PROGRESS`),
  ADD KEY `ID_TASK` (`ID_TASK`),
  ADD KEY `ID_USER` (`ID_USER`);

ALTER TABLE `REWARDS_CATALOGUE`
  ADD PRIMARY KEY (`ID_REWARD`),
  ADD KEY `ID_HOUSEHOLD` (`ID_HOUSEHOLD`),
  ADD KEY `ID_USER` (`ID_USER`),
  ADD KEY `ID_COMPLETION` (`ID_COMPLETION`);

ALTER TABLE `TASK`
  ADD PRIMARY KEY (`ID_TASK`),
  ADD KEY `ID_HOUSEHOLD` (`ID_HOUSEHOLD`),
  ADD KEY `ID_USER` (`ID_USER`);

ALTER TABLE `USER`
  ADD PRIMARY KEY (`ID_USER`),
  ADD UNIQUE KEY `USER_EMAIL` (`USER_EMAIL`);


ALTER TABLE `COMPLETION`
  MODIFY `ID_COMPLETION` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `HOUSEHOLD`
  MODIFY `ID_HOUSEHOLD` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

ALTER TABLE `INVITATION`
  MODIFY `ID_INVITATION` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;

ALTER TABLE `NOTIFICATION`
  MODIFY `ID_NOTIFICATION` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

ALTER TABLE `PROGRESS`
  MODIFY `ID_PROGRESS` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

ALTER TABLE `REWARDS_CATALOGUE`
  MODIFY `ID_REWARD` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

ALTER TABLE `TASK`
  MODIFY `ID_TASK` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

ALTER TABLE `USER`
  MODIFY `ID_USER` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;


ALTER TABLE `COMPLETION`
  ADD CONSTRAINT `completion_ibfk_1` FOREIGN KEY (`ID_TASK`) REFERENCES `TASK` (`ID_TASK`) ON DELETE CASCADE,
  ADD CONSTRAINT `completion_ibfk_2` FOREIGN KEY (`SUBMITTED_BY`) REFERENCES `USER` (`ID_USER`),
  ADD CONSTRAINT `completion_ibfk_3` FOREIGN KEY (`APPROVED_BY`) REFERENCES `USER` (`ID_USER`);

ALTER TABLE `HOUSEHOLD_MEMBER`
  ADD CONSTRAINT `household_member_ibfk_1` FOREIGN KEY (`ID_USER`) REFERENCES `USER` (`ID_USER`) ON DELETE CASCADE,
  ADD CONSTRAINT `household_member_ibfk_2` FOREIGN KEY (`ID_HOUSEHOLD`) REFERENCES `HOUSEHOLD` (`ID_HOUSEHOLD`) ON DELETE CASCADE;

ALTER TABLE `INVITATION`
  ADD CONSTRAINT `invitation_ibfk_1` FOREIGN KEY (`ID_HOUSEHOLD`) REFERENCES `HOUSEHOLD` (`ID_HOUSEHOLD`),
  ADD CONSTRAINT `invitation_ibfk_2` FOREIGN KEY (`INVITED_BY`) REFERENCES `USER` (`ID_USER`);

ALTER TABLE `NOTIFICATION`
  ADD CONSTRAINT `notification_ibfk_1` FOREIGN KEY (`ID_USER`) REFERENCES `USER` (`ID_USER`);

ALTER TABLE `POINTS`
  ADD CONSTRAINT `points_ibfk_1` FOREIGN KEY (`ID_USER`) REFERENCES `USER` (`ID_USER`),
  ADD CONSTRAINT `points_ibfk_2` FOREIGN KEY (`ID_HOUSEHOLD`) REFERENCES `HOUSEHOLD` (`ID_HOUSEHOLD`);

ALTER TABLE `PROGRESS`
  ADD CONSTRAINT `progress_ibfk_1` FOREIGN KEY (`ID_TASK`) REFERENCES `TASK` (`ID_TASK`) ON DELETE CASCADE,
  ADD CONSTRAINT `progress_ibfk_2` FOREIGN KEY (`ID_USER`) REFERENCES `USER` (`ID_USER`) ON DELETE CASCADE;

ALTER TABLE `REWARDS_CATALOGUE`
  ADD CONSTRAINT `rewards_catalogue_ibfk_1` FOREIGN KEY (`ID_HOUSEHOLD`) REFERENCES `HOUSEHOLD` (`ID_HOUSEHOLD`) ON DELETE CASCADE,
  ADD CONSTRAINT `rewards_catalogue_ibfk_2` FOREIGN KEY (`ID_USER`) REFERENCES `USER` (`ID_USER`),
  ADD CONSTRAINT `rewards_catalogue_ibfk_3` FOREIGN KEY (`ID_COMPLETION`) REFERENCES `COMPLETION` (`ID_COMPLETION`);

ALTER TABLE `TASK`
  ADD CONSTRAINT `task_ibfk_1` FOREIGN KEY (`ID_HOUSEHOLD`) REFERENCES `HOUSEHOLD` (`ID_HOUSEHOLD`) ON DELETE CASCADE,
  ADD CONSTRAINT `task_ibfk_2` FOREIGN KEY (`ID_USER`) REFERENCES `USER` (`ID_USER`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
