SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `completion` (
  `ID_COMPLETION` int(11) NOT NULL,
  `ID_TASK` int(11) NOT NULL,
  `SUBMITTED_BY` int(11) NOT NULL,
  `APPROVED_BY` int(11) DEFAULT NULL,
  `STATUS` enum('pending','approved','rejected') DEFAULT 'pending',
  `POINTS` int(11) NOT NULL,
  `AI_CONFIDENCE` int(11) DEFAULT NULL,
  `SUBMITTED_AT` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `household` (
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `HOUSEHOLD_NAME` varchar(255) NOT NULL,
  `INVITE_LINK` varchar(1000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `household_member` (
  `ID_USER` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `ROLE` enum('admin','member') NOT NULL DEFAULT 'member'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `invitation` (
  `ID_INVITATION` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `INVITED_EMAIL` varchar(300) NOT NULL,
  `INVITED_BY` int(11) NOT NULL,
  `STATUS` varchar(20) DEFAULT 'pending'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `notification` (
  `ID_NOTIFICATION` int(11) NOT NULL,
  `ID_USER` int(11) NOT NULL,
  `NOTIFICATION_TITLE` varchar(255) DEFAULT NULL,
  `NOTIFICATION_MESSAGE` varchar(1000) DEFAULT NULL,
  `IS_READ` tinyint(1) DEFAULT 0,
  `NOTIFICATION_CREATED` datetime DEFAULT current_timestamp(),
  `NOTIFICATION_TYPE` varchar(30) NOT NULL,
  `REFERENCE_ID` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `points` (
  `ID_USER` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `TOTAL_POINTS` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `rewards_catalogue` (
  `ID_REWARD` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `ID_USER` int(11) DEFAULT NULL,
  `ID_COMPLETION` int(11) DEFAULT NULL,
  `REWARD_NAME` varchar(255) NOT NULL,
  `REWARD_DESCRIPTION` text DEFAULT NULL,
  `POINTS_TO_DISCOUNT` int(11) NOT NULL,
  `IS_ACTIVE` tinyint(1) DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `task` (
  `ID_TASK` int(11) NOT NULL,
  `ID_HOUSEHOLD` int(11) NOT NULL,
  `ID_USER` int(11) DEFAULT NULL,
  `TASK_NAME` varchar(255) NOT NULL,
  `TASK_DESCRIPTION` text DEFAULT NULL,
  `TASK_POINT` int(11) NOT NULL,
  `TASK_IMAGE` longblob DEFAULT NULL,
  `IS_COLLABORATIVE` tinyint(1) DEFAULT 0,
  `TASK_CREATED` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE `user` (
  `ID_USER` int(11) NOT NULL,
  `USER_NAME` varchar(255) NOT NULL,
  `USER_EMAIL` varchar(255) NOT NULL,
  `USER_PASSWORD` varchar(255) NOT NULL,
  `AVATAR` longblob DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


ALTER TABLE `completion`
  ADD PRIMARY KEY (`ID_COMPLETION`),
  ADD KEY `ID_TASK` (`ID_TASK`),
  ADD KEY `SUBMITTED_BY` (`SUBMITTED_BY`),
  ADD KEY `APPROVED_BY` (`APPROVED_BY`);

ALTER TABLE `household`
  ADD PRIMARY KEY (`ID_HOUSEHOLD`);

ALTER TABLE `household_member`
  ADD PRIMARY KEY (`ID_USER`,`ID_HOUSEHOLD`),
  ADD KEY `ID_HOUSEHOLD` (`ID_HOUSEHOLD`);

ALTER TABLE `invitation`
  ADD PRIMARY KEY (`ID_INVITATION`),
  ADD KEY `ID_HOUSEHOLD` (`ID_HOUSEHOLD`),
  ADD KEY `INVITED_BY` (`INVITED_BY`);

ALTER TABLE `notification`
  ADD PRIMARY KEY (`ID_NOTIFICATION`),
  ADD KEY `ID_USER` (`ID_USER`),
  ADD KEY `REFERENCE_ID` (`REFERENCE_ID`);

ALTER TABLE `points`
  ADD PRIMARY KEY (`ID_USER`,`ID_HOUSEHOLD`),
  ADD KEY `ID_HOUSEHOLD` (`ID_HOUSEHOLD`);

ALTER TABLE `rewards_catalogue`
  ADD PRIMARY KEY (`ID_REWARD`),
  ADD KEY `ID_HOUSEHOLD` (`ID_HOUSEHOLD`),
  ADD KEY `ID_USER` (`ID_USER`),
  ADD KEY `ID_COMPLETION` (`ID_COMPLETION`);

ALTER TABLE `task`
  ADD PRIMARY KEY (`ID_TASK`),
  ADD KEY `ID_HOUSEHOLD` (`ID_HOUSEHOLD`),
  ADD KEY `ID_USER` (`ID_USER`);

ALTER TABLE `user`
  ADD PRIMARY KEY (`ID_USER`),
  ADD UNIQUE KEY `USER_EMAIL` (`USER_EMAIL`);


ALTER TABLE `completion`
  MODIFY `ID_COMPLETION` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `household`
  MODIFY `ID_HOUSEHOLD` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `invitation`
  MODIFY `ID_INVITATION` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `notification`
  MODIFY `ID_NOTIFICATION` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `rewards_catalogue`
  MODIFY `ID_REWARD` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `task`
  MODIFY `ID_TASK` int(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `user`
  MODIFY `ID_USER` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `completion`
  ADD CONSTRAINT `completion_ibfk_1` FOREIGN KEY (`ID_TASK`) REFERENCES `task` (`ID_TASK`) ON DELETE CASCADE,
  ADD CONSTRAINT `completion_ibfk_2` FOREIGN KEY (`SUBMITTED_BY`) REFERENCES `user` (`ID_USER`),
  ADD CONSTRAINT `completion_ibfk_3` FOREIGN KEY (`APPROVED_BY`) REFERENCES `user` (`ID_USER`);

ALTER TABLE `household_member`
  ADD CONSTRAINT `household_member_ibfk_1` FOREIGN KEY (`ID_USER`) REFERENCES `user` (`ID_USER`) ON DELETE CASCADE,
  ADD CONSTRAINT `household_member_ibfk_2` FOREIGN KEY (`ID_HOUSEHOLD`) REFERENCES `household` (`ID_HOUSEHOLD`) ON DELETE CASCADE;

ALTER TABLE `invitation`
  ADD CONSTRAINT `invitation_ibfk_1` FOREIGN KEY (`ID_HOUSEHOLD`) REFERENCES `household` (`ID_HOUSEHOLD`),
  ADD CONSTRAINT `invitation_ibfk_2` FOREIGN KEY (`INVITED_BY`) REFERENCES `user` (`ID_USER`);

ALTER TABLE `notification`
  ADD CONSTRAINT `notification_ibfk_1` FOREIGN KEY (`ID_USER`) REFERENCES `user` (`ID_USER`);

ALTER TABLE `points`
  ADD CONSTRAINT `points_ibfk_1` FOREIGN KEY (`ID_USER`) REFERENCES `user` (`ID_USER`),
  ADD CONSTRAINT `points_ibfk_2` FOREIGN KEY (`ID_HOUSEHOLD`) REFERENCES `household` (`ID_HOUSEHOLD`);

ALTER TABLE `rewards_catalogue`
  ADD CONSTRAINT `rewards_catalogue_ibfk_1` FOREIGN KEY (`ID_HOUSEHOLD`) REFERENCES `household` (`ID_HOUSEHOLD`) ON DELETE CASCADE,
  ADD CONSTRAINT `rewards_catalogue_ibfk_2` FOREIGN KEY (`ID_USER`) REFERENCES `user` (`ID_USER`),
  ADD CONSTRAINT `rewards_catalogue_ibfk_3` FOREIGN KEY (`ID_COMPLETION`) REFERENCES `completion` (`ID_COMPLETION`);

ALTER TABLE `task`
  ADD CONSTRAINT `task_ibfk_1` FOREIGN KEY (`ID_HOUSEHOLD`) REFERENCES `household` (`ID_HOUSEHOLD`) ON DELETE CASCADE,
  ADD CONSTRAINT `task_ibfk_2` FOREIGN KEY (`ID_USER`) REFERENCES `user` (`ID_USER`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
